# Deep Learning Course - LAB 1

## Intro to PyTorch

PyTorch (PT) is a Python (and C++ and Java) library for Machine Learning (ML) particularly suited for Neural Networks and their applications.

Its great selection of built-in modules, models, functions, CUDA capability, tensor arithmetic support and automatic differentiation functionality make it one of the most used scientific libraries for Deep Learning.

Note: for this series of labs, we advise to install Python >= 3.8

### Installing PyTorch

We advise to install PyTorch following the directions given in its [home page](https://pytorch.org/get-started/locally/). Just typing `pip install torch` may not be the correct action as you have to take into account the compatibility with `cuda`. If you have `cuda` installed, you can find your version by typing `nvcc --version` in a terminal (Linux/iOS). We suggest installing PyTorch inside a Conda environment as for the link indicated before.

If you're using Windows, we first suggest first to install Anaconda and then install PyTorch from the `anaconda prompt` software via `conda` (preferably) or `pip`.

If you're using Google Colab, all the libraries needed to follow this lecture should be pre-installed there.

We see now how to operate on Colab.

### For Colab users

Google Colab is a handy tool that we suggest you use for this course---especially if your laptop does not support CUDA or has limited hardware capabilities. Anyway, note that **we'll try to avoid GPU code as much as possible**.

Essentially, Colab renders available to you a virtual machine with a limited hardware capability and disk where you can execute your code inside a given time window. You can even ask for a GPU (if you use it too much you'll need to start waiting a lot before it's available though).

#### Your (maybe) first Colab commands

Colab Jupyter-style notebook interface with a few tweaks.

For instance, you may run (some) bash command from here prepending `!` to your code.

In [9]:
!ls

01-intro-to-pt.ipynb


In [10]:
!pwd

/home/francesco/Desktop/dssc/deeplearning/dl_course/labs


In [11]:
!git clone https://github.com/mnzluca/IntroToAI

Cloning into 'IntroToAI'...
remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 105 (delta 13), reused 26 (delta 5), pack-reused 66
Receiving objects: 100% (105/105), 51.55 MiB | 8.52 MiB/s, done.
Resolving deltas: 100% (32/32), done.


This makes it very easy to operate your virtual machine without the need for a terminal. 

#### File transfer on Colab

One of the most intricate action in Colab is file transfer. Since your files reside on the virtual machine, there're two main ways to operate file transfer on Colab.

* `files.download()` / `.upload()`

In [12]:
from google.colab import files
files.upload()

ModuleNotFoundError: No module named 'google'

In [ ]:
files.download("sample_data/README.md")

Although it may be much more handy to connect your Google Drive to Colab. Here is a snippet that lets you do this.

In [ ]:
from google.colab import drive

folder_mount = '/content/drive' # Your Drive will be mounted on top of this path

drive.mount(folder_mount)

## For VsCode users

Visual Studio Code works perfectly if you're using conda environments.

Just create your own conda environment, then, on VsCode, hit `Ctrl + Shift + p` and type `Python: select interpreter`. The dropdown menu should list the Python binaries within the envs you have created on your machine.

![](imgs/01/vscode_select_interpreter.jpg)

![](imgs/01/vscode_list_envs.jpg)

Moreover, is you're running a Jupyter Notebook, you may select an interpreter the first time you run a cell during the current session.

### Dive into PyTorch - connections with NumPy

Like NumPy, PyTorch provides its own multidimensional array class, called `Tensor`. `Tensor`s are essentially the equivalent of NumPy `ndarray`s.
If we wish to operate a very superficial comparison between `Tensor` and `ndarray`, we can say that:
* `Tensor` draws a lot of methods from NumPy, although it's missing some. The gap though is getting smaller and smaller each new release of PyTorch
* `Tensor` is more object oriented than `ndarray` and solves some inconsistencies within NumPy
* `Tensor` has CUDA support

In [1]:
import torch
import numpy as np

# create custom Tensor and ndarray
x = torch.Tensor([[1,5,4],[3,2,1]])
y = np.array([[1,5,4],[3,2,1]])

def pretty_print(obj, title=None):
    if title is not None:
        print(title)
    print(obj)
    print("\n")

pretty_print(x, "x")
pretty_print(y, "y")

x
tensor([[1., 5., 4.],
        [3., 2., 1.]])


y
[[1 5 4]
 [3 2 1]]




What are the types of these objs?

In [16]:
x.dtype, y.dtype

(torch.float32, dtype('int64'))

`torch` already thinks with Machine Learning in mind as the `Tensor` is implicitly converted to `dtype float32`, while NumPy makes no such assumption.

For more info on `Tensor` data types, please check the beginning of [this page](https://pytorch.org/docs/stable/tensors.html). We can use `Tensor` methods such as `.half()` or `.bool()` to convert the tensor from `float32` to `float16` or `bool` respectively.

As in NumPy, we can call the `.shape` attribute to get the shape of the structures. Moreover, `Tensor`s have also the `.size()` method which is analogous to `.shape`.

In [17]:
x.shape, y.shape, x.size()

(torch.Size([2, 3]), (2, 3), torch.Size([2, 3]))

Notice how a `Tensor` shape is **not** a tuple.

We can also create a random `Tensor` analogously to NumPy.

A `2 × 3 × 3` `Tensor` is the same as saying "2 3 × 3 matrices", or a "cubic matrix"

![](img/tensors.jpg)

In [18]:
x = torch.rand([2, 3, 3])
x

tensor([[[0.9875, 0.3696, 0.8474],
         [0.4265, 0.8342, 0.2753],
         [0.3097, 0.6062, 0.4137]],

        [[0.0314, 0.7634, 0.7945],
         [0.0929, 0.5338, 0.4279],
         [0.2555, 0.1934, 0.6099]]])

In [19]:
y = np.random.rand(2, 3, 3)
y

array([[[0.33163279, 0.88199571, 0.56317543],
        [0.54212913, 0.01772852, 0.60164033],
        [0.96524917, 0.65273472, 0.8313434 ]],

       [[0.98725535, 0.92524922, 0.6320534 ],
        [0.03712309, 0.57980096, 0.60142504],
        [0.30663184, 0.43416144, 0.98777024]]])

We can get the total number of elements in a `Tensor` via the `numel()` method

In [20]:
x.numel()

18

We can get the memory occupied by each element of a `Tensor` via `element_size()`

In [21]:
x.element_size()

4

Hence, we can quickly calculate the size of the `Tensor` within the RAM

In [22]:
x.numel() * x.element_size()

72

#### Slicing a `Tensor`

You can slice a `Tensor` (*i.e.*, extract a substructure of a `Tensor`) as in NumPy using the square brackets:

In [23]:
# extract first element (i.e., matrix) of first dimension
pretty_print(x[0], "Slice first element (x[0])")

# extract a specific element
pretty_print(x[1,2,0], "Slice element at (1, 2, 0) (x[1, 2, 0])")

# extract first element of second dimension (":" means all the elements of the given dim)
pretty_print(x[:, 0], "Slice first element of second dim (x[:, 0])")

# note that it is equivalent to
pretty_print(x[:, 0, :], "As above (x[:, 0] equivalent to x[:, 0, :])")

# extract range of dimensions (first and second element of third dim) 
pretty_print(x[:, :, 0:2], "Slice first and second el of third dim (x[:, :, 0:2])")

# note that it is equivalent to (i.e., you can also pass list for slicing, as opposed to Py vanilla lists/tuples)
pretty_print(x[:, :, (0, 1)], "As above (x[:, :, 0:2] equivalent to x[:, :, (0, 1)])")

Slice first element (x[0])
tensor([[0.9875, 0.3696, 0.8474],
        [0.4265, 0.8342, 0.2753],
        [0.3097, 0.6062, 0.4137]])


Slice element at (1, 2, 0) (x[1, 2, 0])
tensor(0.2555)


Slice first element of second dim (x[:, 0])
tensor([[0.9875, 0.3696, 0.8474],
        [0.0314, 0.7634, 0.7945]])


As above (x[:, 0] equivalent to x[:, 0, :])
tensor([[0.9875, 0.3696, 0.8474],
        [0.0314, 0.7634, 0.7945]])


Slice first and second el of third dim (x[:, :, 0:2])
tensor([[[0.9875, 0.3696],
         [0.4265, 0.8342],
         [0.3097, 0.6062]],

        [[0.0314, 0.7634],
         [0.0929, 0.5338],
         [0.2555, 0.1934]]])


As above (x[:, :, 0:2] equivalent to x[:, :, (0, 1)])
tensor([[[0.9875, 0.3696],
         [0.4265, 0.8342],
         [0.3097, 0.6062]],

        [[0.0314, 0.7634],
         [0.0929, 0.5338],
         [0.2555, 0.1934]]])




In Py, you can also slice any list by interval via the "double colon" notation `::` (`from` : `(to - 1)` :`step`). Note that `::3` means "take all elements of the object by step of 3 starting from 0 until the list ends".

In [24]:
torch.arange(0, 10)[0:7:3]

tensor([0, 3, 6])

#### `Tensor` supports linear algebra

In [25]:
z1 = torch.rand([4, 5])
print("z1")
print("shape", z1.shape)
print(z1)

# transposition
z2 = z1.T

print("\nz2")
print("shape", z2.shape)
print(z2)

z1
shape torch.Size([4, 5])
tensor([[0.7653, 0.8534, 0.5285, 0.8342, 0.4809],
        [0.8608, 0.9645, 0.3755, 0.0715, 0.3104],
        [0.9661, 0.5895, 0.9135, 0.6129, 0.4838],
        [0.7773, 0.6064, 0.0437, 0.4200, 0.2028]])

z2
shape torch.Size([5, 4])
tensor([[0.7653, 0.8608, 0.9661, 0.7773],
        [0.8534, 0.9645, 0.5895, 0.6064],
        [0.5285, 0.3755, 0.9135, 0.0437],
        [0.8342, 0.0715, 0.6129, 0.4200],
        [0.4809, 0.3104, 0.4838, 0.2028]])


In [26]:
# matrix multiplication
pretty_print(z1 @ z2, "Matrix multiplication: with '@'")

# equivalent to
pretty_print(torch.matmul(z1, z2), "Matrix multiplication: with torch.matmul")

# and also
pretty_print(z1.matmul(z2), "Matrix multiplication: with Tensor.matmul")

Matrix multiplication: with '@'
tensor([[2.5203, 1.8892, 2.4691, 1.5833],
        [1.8892, 1.9136, 1.9371, 1.3633],
        [2.4691, 1.9371, 2.7250, 1.5039],
        [1.5833, 1.3633, 1.5039, 1.1913]])


Matrix multiplication: with torch.matmul
tensor([[2.5203, 1.8892, 2.4691, 1.5833],
        [1.8892, 1.9136, 1.9371, 1.3633],
        [2.4691, 1.9371, 2.7250, 1.5039],
        [1.5833, 1.3633, 1.5039, 1.1913]])


Matrix multiplication: with Tensor.matmul
tensor([[2.5203, 1.8892, 2.4691, 1.5833],
        [1.8892, 1.9136, 1.9371, 1.3633],
        [2.4691, 1.9371, 2.7250, 1.5039],
        [1.5833, 1.3633, 1.5039, 1.1913]])




Note that `@` identifies the matrix product.

Don't mistake `@` and `*` as the latter is the Hadamard (element-by-element) product!

#### Question: is it possible to do scalar product between vectors?

Note: the scalar product is also called [inner or dot or projection product](https://en.wikipedia.org/wiki/Dot_product).

Like we have seen with matrices, we can proceed as follows for vectors:

In [27]:
vec1 = torch.rand((5,))
vec2 = torch.rand((5,))

pretty_print(vec1, "vec1")
pretty_print(vec2, "vec2")

pretty_print(vec1 @ vec2, "I can use '@' even if the two vectors aren't conformable (i.e. both colum or row vectors")

pretty_print(vec1.unsqueeze(0) @ vec2.unsqueeze(-1), "This is the 'classical' inner product between row and column vector -- Notice the dim of the output")

pretty_print(torch.matmul(vec1, vec2), "Notice that the same result can be achieved via the `matmul` method of torch -- as we have seen, it's the inner product")

pretty_print(torch.dot(vec1, vec2), "...and also via torch.dot")

vec1
tensor([0.8323, 0.1770, 0.9439, 0.5592, 0.6208])


vec2
tensor([0.2641, 0.9689, 0.3940, 0.3166, 0.9162])


I can use '@' even if the two vectors aren't conformable (i.e. both colum or row vectors
tensor(1.5090)


This is the 'classical' inner product between row and column vector -- Notice the dim of the output
tensor([[1.5090]])


Notice that the same result can be achieved via the `matmul` method of torch -- as we have seen, it's the inner product
tensor(1.5090)


...and also via torch.dot
tensor(1.5090)




In [41]:
# dot works only with vectors!
torch.dot(torch.rand((3,4)), torch.rand(4,3))

# do this instead!
torch.matmul(torch.rand((3,4)), torch.rand(4,3))

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

On to the tutorial, let us see more examples of operations on tensors and conformability between tensors....

In [42]:
z1 * z2 # this gives an Exception

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [43]:
z1 * z1

tensor([[0.5856, 0.7283, 0.2793, 0.6958, 0.2313],
        [0.7409, 0.9302, 0.1410, 0.0051, 0.0964],
        [0.9333, 0.3475, 0.8345, 0.3757, 0.2341],
        [0.6042, 0.3677, 0.0019, 0.1764, 0.0411]])

Generally, the "regular" arithmetic operators for Python act as element-wise operators in `Tensor`s (as in `ndarrays`)

In [44]:
z1 ** 2 # Equivalent to above

tensor([[0.5856, 0.7283, 0.2793, 0.6958, 0.2313],
        [0.7409, 0.9302, 0.1410, 0.0051, 0.0964],
        [0.9333, 0.3475, 0.8345, 0.3757, 0.2341],
        [0.6042, 0.3677, 0.0019, 0.1764, 0.0411]])

In [45]:
z3 = torch.Tensor([[1,2,3,4,7],[0.2,2,4,5,3],[-1,3,-4,2,2],[1,1,1,1,2]])
pretty_print(z1 % z3, "z1 % z3 (remainder of integer division)")
pretty_print(z3 // z1, "z3 // z1 (integer division)") # integer division
z3 /= z1
pretty_print(z3, "in-place tensor division (z3 /= z1)")

z1 % z3 (remainder of integer division)
tensor([[ 0.7653,  0.8534,  0.5285,  0.8342,  0.4809],
        [ 0.0608,  0.9645,  0.3755,  0.0715,  0.3104],
        [-0.0339,  0.5895, -3.0865,  0.6129,  0.4838],
        [ 0.7773,  0.6064,  0.0437,  0.4200,  0.2028]])


z3 // z1 (integer division)
tensor([[ 1.,  2.,  5.,  4., 14.],
        [ 0.,  2., 10., 69.,  9.],
        [-1.,  5., -4.,  3.,  4.],
        [ 1.,  1., 22.,  2.,  9.]])


in-place tensor division (z3 /= z1)
tensor([[ 1.3067,  2.3436,  5.6768,  4.7952, 14.5549],
        [ 0.2324,  2.0737, 10.6519, 69.9422,  9.6647],
        [-1.0351,  5.0894, -4.3787,  3.2629,  4.1336],
        [ 1.2865,  1.6492, 22.8596,  2.3810,  9.8612]])




/tmp/ipykernel_8523/3229365867.py:3: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  pretty_print(z3 // z1, "z3 // z1 (integer division)") # integer division


In some PyTorch-based libraries, you will also see things like

In [46]:
z3.mul(z1)
#this is equivalent to z3*z1

tensor([[ 1.0000,  2.0000,  3.0000,  4.0000,  7.0000],
        [ 0.2000,  2.0000,  4.0000,  5.0000,  3.0000],
        [-1.0000,  3.0000, -4.0000,  2.0000,  2.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000,  2.0000]])

or, for in-place operations, you will also see

In [47]:
z3.mul_(z1)

tensor([[ 1.0000,  2.0000,  3.0000,  4.0000,  7.0000],
        [ 0.2000,  2.0000,  4.0000,  5.0000,  3.0000],
        [-1.0000,  3.0000, -4.0000,  2.0000,  2.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000,  2.0000]])

this also applies to other operations (not necessarily arithmetical, also boolean):

In [14]:
pretty_print(z3 == z3 ** 2, "In the Pythonic way (z3 == z3 ** 2)...")

pretty_print(z3.eq(z3.pow(2)), "...and in the 'PyTorch' way (z3.eq(z3.pow(2))")

NameError: name 'z3' is not defined

PyTorch abides to one of Python unwritten rules: method names ending with a single "_" and not starting with one are meant to indicate in-place operations, which mutate the object they're called from.

As for `ndarrays`, `Tensor`s arithmetic operations support **broadcasting**. Roughly speaking, when two `Tensor`s have different shapes and a binary operator is applied to them, PT will try to find a way to make these objects "compatible" for the operation. 

Of course, broadcasting is not always possible, but as a rule of thumb, if some dimensions of a `Tensor` are one and the other dimensions are the same, broadcasting works.

In [15]:
small_vector_5 = torch.Tensor([1,2,3,5,2]) # this is treated as a row vector (1 x 5 matrix)
print("small_vector_5:", small_vector_5, "; Shape:", small_vector_5.shape, "\n")

pretty_print(z1 / small_vector_5, "Broadcasting: dividing matrix by row vector")

small_vector_4 = torch.Tensor([4,2,3,1])
small_vector_4 = small_vector_4.unsqueeze(-1) # this operation "transposes" the vector into a column vector (4 x 1 matrix)
print("small_vector_4:\n", small_vector_4, "\nShape:", small_vector_4.shape, "\n")

pretty_print(z1 / small_vector_4, "Broadcasting: dividing matrix by column vector")

small_vector_5: tensor([1., 2., 3., 5., 2.]) ; Shape: torch.Size([5]) 



NameError: name 'z1' is not defined

In [16]:
torch.Tensor([1,2,3]) == torch.Tensor([[1,2,3]]) # single-dim Tensors are also row vectors

tensor([[True, True, True]])

#### Reshaping and permuting

Sometimes it may be necessary to reshape the tensors to apply some specific operators.

Take the example of RGB images: they can be seen as `3 x h x w` tensors, where `h` is the height and `w` the width.

![](img/image_tensor.png)

Sometimes, it may be necessary to "flatten" the three matrices into vectors, thus obtaining a `3 x hw` tensor.

In [17]:
image = torch.load("data/img.pt")
image.shape

FileNotFoundError: [Errno 2] No such file or directory: 'data/img.pt'

This flattening may be achieved via the `reshape` method.

In [ ]:
image_reshaped = image.reshape(3, 243*880)
pretty_print(image_reshaped.shape, "shape of image_reshaped")

shape of image_reshaped
torch.Size([3, 213840])




We can alternatively use the `view` method...

In [18]:
image_view = image.view(3, 243*880)
pretty_print(image_view.shape, "shape of image_view")

NameError: name 'image' is not defined

**Q**: what is the difference between `reshape` and `view`?

* `view` does not copy the object. It's just a _view_ of the original tensor.
* `reshape` sometimes copy the object, sometimes it does not and resorts to `view` 

The cases when the two methods behave differently are marginal and we don't have time to discuss that here (you can see for instance [this stackoverflow](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)).

As a general rule, use `reshape` instead of `view` because the latter may throw unexpected errors, while with the former you're always sure your code will run seamlessly.


Some libraries encode images as `h x w x 3` tensors instead of `3 x h x w`.

To convert between these two format, one may be tempted to `reshape` or `view` the tensor: in the end, they share the number of elements.



In [19]:
from matplotlib import pyplot as plt

image2 = image.reshape(243, 880, 3)

plt.imshow(image2)
plt.show()

NameError: name 'image' is not defined

That does not seem to work though: reshape does not change the order of the elements within the memory.

In order to do so, we need to use `permute`, which changes shape **and** the order of the elements.
We need to pass the new order of the dimensions to it.

In [20]:
image3 = image.permute(1,2,0) # 1,2,0 --> old dim1 goes first, old dim2 goes second, dim0 goes last
# can also do image.permute(-2,-1,0) -- works with negative indices as well
plt.imshow(image3)
plt.show()

NameError: name 'image' is not defined

#### More linear algebra

In [21]:
z3_norm = z3.norm()
pretty_print(z3_norm, "Tensor norm")
pretty_print(np.linalg.norm(z3), "ndarray norm") # notice how torch is more OO

NameError: name 'z3' is not defined

Notice how methods reducing `Tensor`s to scalars still return singleton `Tensor`s. (be wary of this feature when scripting something in PT)

To "disentangle" the scalar from a `Tensor` use the `.item()` method.

In [22]:
z3_norm.item()

NameError: name 'z3_norm' is not defined

Note that, as for NumPy, PT supports `Tensor`s operator on a subset of its dimensions.

For example, given a `3x4x4 Tensor`, we might want to calculate the norm of each of the three `4x4` matrices composing it. We must hence specify to the `norm` method the dimensions on which we want it to operate the reduction:

In [23]:
z4 = torch.rand((3,4,5))
pretty_print(z4, "z4")
pretty_print(z4.norm(dim=(1,2)), "Norm of the three matrices composing z4 -- z4.norm(dim=(1,2))")

z4
tensor([[[0.4894, 0.0325, 0.1853, 0.3709, 0.3124],
         [0.8639, 0.4254, 0.0319, 0.7132, 0.4886],
         [0.0025, 0.1250, 0.6168, 0.1127, 0.3918],
         [0.0360, 0.5314, 0.2885, 0.2615, 0.1495]],

        [[0.6051, 0.1959, 0.0275, 0.4453, 0.2003],
         [0.1477, 0.3756, 0.4171, 0.0315, 0.4269],
         [0.3869, 0.7154, 0.3278, 0.2791, 0.2045],
         [0.0120, 0.5254, 0.7148, 0.6957, 0.9907]],

        [[0.7426, 0.3493, 0.7740, 0.2887, 0.4095],
         [0.9613, 0.1946, 0.9515, 0.9634, 0.8514],
         [0.2664, 0.2776, 0.0176, 0.9121, 0.6002],
         [0.0770, 0.5164, 0.3122, 0.1863, 0.3588]]])


Norm of the three matrices composing z4 -- z4.norm(dim=(1,2))
tensor([1.7904, 2.0748, 2.6302])




As expected, the result is a `1x3 Tensor`, showing the norm of each of the matrices.

We can notice this behaviour in other `Tensor` operator applying a reduction, for example `.sum()` and `.prod()` (sum/product of the elements within the tensor).

By specifying `z4.prod(dim=1)`, we **fix** the second dimension and loop through the other dimensions, applying the product for all of the resulting tensor slices. Let's see a code for clarity.

In [24]:
# 1. let us create an empty vector with the shape of the dimension we did NOT specify in `prod` above:
product_fix_dim = torch.empty([z4.shape[0], z4.shape[2]])

# 2. we loop through these dimensions to get the result of `z4.prod(dim=1)`
for i in range(product_fix_dim.shape[0]):
    for j in range(product_fix_dim.shape[1]):
        # the result for the (i,j) position is the product of the corresponding sub-tensor z4[i, :, j]
        # (we consider the whole of the 2nd dim, loop through the 1st and 3rd)
        product_fix_dim[i, j] = z4[i, :, j].prod()

pretty_print(product_fix_dim, "The result of our fancy loop ...")
pretty_print(z4.prod(dim=1), "... is the same as z4.prod(dim=1)")

The result of our fancy loop ...
tensor([[3.8491e-05, 9.1767e-04, 1.0510e-03, 7.7968e-03, 8.9429e-03],
        [4.1605e-04, 2.7659e-02, 2.6850e-03, 2.7217e-03, 1.7324e-02],
        [1.4654e-02, 9.7480e-03, 4.0550e-03, 4.7258e-02, 7.5086e-02]])


... is the same as z4.prod(dim=1)
tensor([[3.8491e-05, 9.1767e-04, 1.0510e-03, 7.7968e-03, 8.9429e-03],
        [4.1605e-04, 2.7659e-02, 2.6850e-03, 2.7217e-03, 1.7324e-02],
        [1.4654e-02, 9.7480e-03, 4.0550e-03, 4.7258e-02, 7.5086e-02]])




Analogously, we may apply the same reasoning to the `sum()` method:

`z4.sum(dim=0)`:
* we fix the first dim
* and loop through the other dims

In [25]:
pretty_print(z4.sum(dim=0), "z4.sum(dim=0) -- Element-wise sum of the three matrices composing the tensor -- is a 4x5 matrix")

z4.sum(dim=0) -- Element-wise sum of the three matrices composing the tensor -- is a 4x5 matrix
tensor([[1.8372, 0.5777, 0.9868, 1.1049, 0.9222],
        [1.9729, 0.9957, 1.4004, 1.7081, 1.7669],
        [0.6558, 1.1181, 0.9622, 1.3039, 1.1965],
        [0.1251, 1.5732, 1.3155, 1.1434, 1.4990]])




this is analogous to

In [26]:
z4[0] + z4[1] + z4[2]

tensor([[1.8372, 0.5777, 0.9868, 1.1049, 0.9222],
        [1.9729, 0.9957, 1.4004, 1.7081, 1.7669],
        [0.6558, 1.1181, 0.9622, 1.3039, 1.1965],
        [0.1251, 1.5732, 1.3155, 1.1434, 1.4990]])

#### Seamless conversion from NumPy to PT

In [27]:
y_numpy = np.random.rand(3,5)
y_torch = torch.from_numpy(y_numpy)
pretty_print(y_torch, "y converted to torch.Tensor")

x = torch.rand(6,4)
x_numpy = x.numpy()
pretty_print(x_numpy, "x converted to numpy.ndarray")

# Note that NumPy implicitly converts Tensor to ndarray whenever it can; the same doesn't happen for PT
pretty_print(np.linalg.norm(x), "Example of implicit conversion Tensor → ndarray (np.linalg.norm(x) where x is torch.tensor)")

torch.norm(x_numpy) # this does not work

y converted to torch.Tensor
tensor([[0.8589, 0.2457, 0.1844, 0.2150, 0.9266],
        [0.7847, 0.7004, 0.7023, 0.8426, 0.2721],
        [0.7488, 0.2254, 0.4422, 0.1403, 0.6795]], dtype=torch.float64)


x converted to numpy.ndarray
[[0.5581243  0.8674133  0.52763915 0.7401994 ]
 [0.19616401 0.3515218  0.6959443  0.7635181 ]
 [0.2300492  0.9805852  0.5412167  0.97590816]
 [0.089248   0.40482777 0.96061003 0.05313951]
 [0.68500036 0.686145   0.73145944 0.98537284]
 [0.9623947  0.8212372  0.8838779  0.9487144 ]]


Example of implicit conversion Tensor → ndarray (np.linalg.norm(x) where x is torch.tensor)
3.4935265




AttributeError: 'numpy.ndarray' object has no attribute 'dim'

#### Stochastic functionalities

We can render the (pseudo)random number generator deterministic by calling `torch.manual_seed(integer)`.

This works for both CPU and CUDA RNG calls.

In [28]:
torch.manual_seed(123456)
print("...from now on our random tensor should be the same...")

...from now on our random tensor should be the same...


In [29]:
pretty_print(torch.randperm(10), "(randperm) Random permutation of 0:10")

pretty_print(torch.rand_like(z1), "(rand_like) Create random vector with the same shape of z_1")

pretty_print(torch.randint(10, (3, 3)), "(randint) Like rand, but with integers up to 10")

pretty_print(torch.normal(0, 1, (3, 3)), "(normal) Sampling a 3x3 iid scalars from N(0,1)")

pretty_print(torch.normal(torch.Tensor([[1,2,3],[4,5,6],[0,0,0]]), torch.Tensor([[1,0.5,0.9],[0.5,1,0.1],[3,4,1]])), "Sampling from 9 normals with different means and std into a (3x3) Tensor")

(randperm) Random permutation of 0:10
tensor([5, 2, 4, 9, 1, 7, 3, 6, 0, 8])




NameError: name 'z1' is not defined

### Using GPUs

All `Torch.Tensor` methods support GPU computation via built-in CUDA wrappers.

Just transfer the involved `Tensor`s to CUDA and let the magic happen :)

In [30]:
# check if cuda is available on this machine
torch.cuda.is_available()

has_cuda_gpu = torch.cuda.is_available()

In [31]:
print(has_cuda_gpu)

False


In [32]:
if has_cuda_gpu:
    dim = 10000
    large_cpu_matrix = torch.rand((dim, dim)) 
    large_gpu_matrix = large_cpu_matrix.to("cuda") # Can also specify "cuda:gpu_id" if multiple GPUs
    # alternatively, you may also call large_cpu_matrix.cuda() or large_cpu_matrix.cuda(0)
else:
    print("Sorry, this part of the notebook is inaccessible since it seems you don't have a CUDA-capable GPU on your device :/")

Sorry, this part of the notebook is inaccessible since it seems you don't have a CUDA-capable GPU on your device :/


In [33]:
pretty_print(large_cpu_matrix.device, "Device of large_cpu_matrix")
pretty_print(large_gpu_matrix.device, "Device of large_gpu_matrix")
pretty_print(large_gpu_matrix, "If a tensor is not on CPU, the device will also be printed if you print the tensor itself")

NameError: name 'large_cpu_matrix' is not defined

In [69]:
if has_cuda_gpu:
    import timeit

    # NOTE: please fix this number w.r.t. your GPU and CPU
    repetitions = 100

    print("Norm of large cpu matrix. Time:", timeit.timeit("large_cpu_matrix.norm()", number=repetitions, globals=locals()))
    print("Norm of large gpu matrix. Time:", timeit.timeit("large_gpu_matrix.norm()", number=repetitions, globals=locals()))
else:
    print("Sorry, this part of the notebook is inaccessible since it seems you don't have a CUDA-capable GPU on your device :/")

Norm of large cpu matrix. Time: 3.758484651999879
Norm of large gpu matrix. Time: 0.015846973999941838


In [70]:
large_cpu_matrix2 = torch.rand((dim, dim))


print("Norm of large cpu matrix. Time:", timeit.timeit("large_cpu_matrix.norm()", number=100, globals=locals()))
print("Norm of large gpu matrix. Time:", timeit.timeit("large_cpu_matrix.cuda().norm()", number=100, globals=locals()))

Norm of large cpu matrix. Time: 3.7309527239999625
Norm of large gpu matrix. Time: 10.428168874999756


**Q**: Why that difference between the first and the second cells?



Captain obvious: Use `tensor.cpu()` or `tensor.to("cpu")` to move a tensor to your CPU

### Building easy ML models

By using all the pieces we've seen till now, we can build our first ML model using PyTorch: a linear regressor, whose model is

$y = XW + b$

which can also be simplified as

$y = XW$

if we incorporate the bias $b$ inside $W$ and add to the $X$ a column of ones to the right.

![](imgs/01/fakedata.jpg)

We'll first create our data. The $X$ 's are the 0:9 range plus some iid white noise, while the $y$ is just the 0:9 range

In [2]:
x1 = torch.arange(0, 10).float().unsqueeze(-1)
x2 = torch.arange(0, 10).float().unsqueeze(-1)
x3 = torch.arange(0, 10).float().unsqueeze(-1)
x0 = torch.ones([10]).float().unsqueeze(-1)
# first, concatenate x1, x2, and x3 to form a single matrix X
X = torch.cat((x1, x2, x3), dim=1)
# add small noise to the Xs, so that we don't have a trivial "interpolation" problem
eps = torch.normal(0, .3, (10, 3))
X += eps
# concatenate also x0 so we can express the model as y=XW
X = torch.cat((X, x0), dim=1)

pretty_print(X, "X (covariates)")


X (covariates)
tensor([[0.0742, 0.3453, 0.3252, 1.0000],
        [1.3821, 0.8403, 1.0003, 1.0000],
        [2.4326, 1.1355, 2.1646, 1.0000],
        [3.6870, 3.1215, 3.0320, 1.0000],
        [4.4748, 4.2018, 4.0512, 1.0000],
        [5.3662, 4.5358, 4.8595, 1.0000],
        [5.5035, 6.4922, 6.0556, 1.0000],
        [7.0286, 7.0342, 6.7601, 1.0000],
        [8.1340, 7.7071, 7.9352, 1.0000],
        [9.1925, 9.4462, 8.9605, 1.0000]])




**Q**: how can we obtain the same `X` but first concatenating, then summing the white noise?

In [3]:
y = torch.arange(0, 10).float().unsqueeze(-1)

pretty_print(y, "y (response)")

y (response)
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])




For the case of linear regression, we usually wish to obtain a set of weights minimizing the so called mean square error/loss (MSE), which is the squared difference between the ground truth and the model prediction, summed for each data instance.

We know that the OLS/Max Likelihood esitmator is the one yielding the optimal set of weights in that regard.

$\hat{W} = (X^\top X)^{-1} X^\top y$

In [4]:
W_hat = ((X.T @ X).inverse()) @ X.T @ y # OLS estimator

pretty_print(W_hat, "W (optimal weights/coefficients [first 3] and bias/intercept [last one])")

W (optimal weights/coefficients [first 3] and bias/intercept [last one])
tensor([[ 0.2090],
        [ 0.0318],
        [ 0.7938],
        [-0.2135]])




We can evaluate our model on the mean square loss

**Q**: what is its formula?

$L(y,\hat{y}) = \frac{1}{n}  \sum_{i = 1}^{n} (y_i - \hat{y_i})$

In [5]:
def mean_square_loss(y, y_hat):
    return torch.sum((y-y_hat) ** 2)/y.numel()

Let's apply it to our data.

First we need to obtain the predictions, then we can evaluate the MSE.

In [6]:
y_hat = X @ W_hat
pretty_print(y_hat, "Predictions (y_hat)")

pretty_print(mean_square_loss(y, y_hat), "Loss (MSE)")

Predictions (y_hat)
tensor([[0.0711],
        [0.8959],
        [2.0490],
        [3.0628],
        [4.0707],
        [4.9092],
        [5.9495],
        [6.8446],
        [8.0296],
        [9.1200]])


Loss (MSE)
tensor(0.0077)




#### Using PT built-ins

We will now be exploring the second chunk of PT functionalities, namely the built-in structures and routines supporting the creation of ML models.

We can create the same model we have seen before using PT built-in structures, so we start to see them right away.

Usually, a PT model is a `class` inheriting from `torch.nn.Module`. Inside this class, we'll define two methods:
* the constructor (`__init__`) in which we define the building blocks of our model as class variables (later during our lectures we'll see more "elegant" methods to build models architectures)
* the `forward` method, which specifies how the data fed into the model needs to be processed in order to produce the output

Note for those who already know something about NNs: we don't need to define `backward` methods since we're constructing our model with built-in PT building blocks. PT automatically creates a `backward` routine based upon the `forward` method.

Our model only has one building block (layer) which is a `Linear` layer.
We need to specify the size of the input (i.e. the coefficients `W` of our linear regressor) and the size of the output (i.e. how many scalars it produces) of the layer. We additionaly request our layer to have a bias term `b` (which acts as the intercept of the hyperplane we saw before).

The `Linear` layer processes its input as `XW + b`, which is exactly the (first) equation of the linear regressor we saw before.



In [7]:
class LinearRegressor(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.regressor = torch.nn.Linear(in_features=3, out_features=1, bias=True)

    def forward(self, X):
        return self.regressor(X)

We can create an instance of our model and inspect the current parameters by using the `state_dict` method, which prints the building blocks of our model and their current parameters. Note that `state_dict` is essentially a dictonary indexed by the names of the building blocks which we defined inside the constructor (plus some additional identifiers if a layer has more than one set of parameters).

In [8]:
lin_reg = LinearRegressor()

for param_name, param in lin_reg.state_dict().items():
    print(param_name, param)

regressor.weight tensor([[-0.0021, -0.3715, -0.5584]])
regressor.bias tensor([-0.4237])


We can update the parameters via `state_dict` and re-using the same OLS estimates we obtained before.

Note that PT is thought of for Deep Learning: it does not have (I think) the routines to solve different ML problems.

Next time, we'll see how we can unleash PT's gradient-based iterative training routines and compare the results w.r.t. the OLS estimators.

In [9]:
state_dict = lin_reg.state_dict()
state_dict["regressor.weight"] = W_hat[:3].T
state_dict["regressor.bias"] = W_hat[3]
lin_reg.load_state_dict(state_dict)

<All keys matched successfully>

In [10]:
# Check if it worked
for param_name, param in lin_reg.state_dict().items():
    print(param_name, param)

regressor.weight tensor([[0.2090, 0.0318, 0.7938]])
regressor.bias tensor([-0.2135])


The `forward` method gets implicitly called by passing the data to our model's instance `lin_reg`:

In [11]:
X_lin_reg = X[:,:3]
predictions_lin_reg = lin_reg(X_lin_reg)
pretty_print(predictions_lin_reg, "Predictions of torch class")

Predictions of torch class
tensor([[0.0711],
        [0.8959],
        [2.0490],
        [3.0628],
        [4.0707],
        [4.9092],
        [5.9495],
        [6.8446],
        [8.0296],
        [9.1200]], grad_fn=<AddmmBackward0>)




The predictions are the same as before

In [12]:
pretty_print(y_hat, "Predictions of linear model")

Predictions of linear model
tensor([[0.0711],
        [0.8959],
        [2.0490],
        [3.0628],
        [4.0707],
        [4.9092],
        [5.9495],
        [6.8446],
        [8.0296],
        [9.1200]])




### Adding non-linearity

One of the staples of DL is that the relationship between the `X`s and the predictions is **non-linear**.

The non-linearity is obtain by applying a non-linear function (called *activation function*) after each linear layer.

We can complicate just a little bit our linear model to create a **logistic regressor**:

$y = \text{logistic}(XW + b)$,

where $\text{logistic}(z) = \exp(z) / (1 + \exp(z))$

The logistic function has different names:
* in statistics, it's usually called *inverse logit* as well
* in DL and mathematics, it's called *sigmoid function* due to its "S" shape and is often denoted with the symbol $\sigma$

Hystorically, the sigmoid was between the first activation functions used in NNs.

![](img/sigmoid.png)

Logistic regression is usually used as a **binary classification model** instead of a regression model.
In this setting, we suppose we have two destination classes to which we assign values 0 and 1: `y ∈ {0, 1}`.
Since the codomain of the sigmoid is `[0,1]`, we can interpret its output `ŷ` as a probability value, and assign each data to the class 0 if `ŷ <= 0.5`, to the class 1 otherwise.


In [13]:
y = torch.Tensor([0,1,0,0,1,1,1,0,1,1])
pretty_print(y, "y for our classification problem")

y for our classification problem
tensor([0., 1., 0., 0., 1., 1., 1., 0., 1., 1.])




Note that we may also want our y to be a vector of `int`s.
We can convert the `Tensor` type to `int` by calling the method `.long()` or `.int()` of `Tensor`.
Usually, PT uses the long datatype for labels.

As in NumPy, the type of the `Tensor` is found within the `dtype` variable of the given `Tensor`.

In [14]:
y = y.long()
pretty_print(y, "y converted to int")
pretty_print(y.dtype, "Data type of y")

y converted to int
tensor([0, 1, 0, 0, 1, 1, 1, 0, 1, 1])


Data type of y
torch.int64




Let us now build our logistic regressor in PT.

We only need one single addition wrt the linear regressor: in the `forward` method, we'll add the sigmoidal non-linearity by calling the `sigmoid` function within the `torch.nn.functional` library.

Note that there also exist some "mirror" alias of these functionals within `torch.nn` (e.g. `torch.nn.Sigmoid`): we'll learn in the following lecture why these aliases are there and how to use them.

In [17]:
class LogisticRegressor(torch.nn.Module):
    def __init__(self):
        super().__init__()
        # no difference wrt linear regressor
        self.regressor = torch.nn.Linear(in_features=3, out_features=1)
    
    def forward(self, X):
        out = self.regressor(X)
        # here we apply the sigmoid fct to the output of regressor
        out = torch.sigmoid(out)
        return out
#actually you can do better

class BetterLogisticRegressor(LinearRegressor):
    def __init__(self):
        super().__init__()
    def forward(self,x):
        return torch.sigmoid(super().forward(x))

We can instantiate our logistic regressor and use it to calculate our predictions on the same X as before.

Note that **we're using the initial (random) weights which PT has assigned to the model parameters**.
For our linear regressor, we were able to analytically obtain the OLS value of the parameters.
In the case of logistic regression, there's no MaxLikelihood estimator obtainable in close form and we need to resort to numerical methods to obtain them.
Since the part concerning numerical optimization will be discussed during the next Lab, we will not be training our model (hence results will obviously be sub-par).

In [18]:
log_reg = BetterLogisticRegressor()
y_hat = log_reg(X_lin_reg)
pretty_print(y_hat, "logistic regressor predictions")

logistic regressor predictions
tensor([[0.5656],
        [0.4965],
        [0.4071],
        [0.3741],
        [0.3279],
        [0.2731],
        [0.2650],
        [0.2090],
        [0.1597],
        [0.1382]], grad_fn=<SigmoidBackward0>)




There exist many ways to evaluate the performance of the logistic regressor: one of them is **accuracy** (correctly identified units / total number of units).
We can define a function to evaluate accuracy and calculate it on our model and data

In [19]:
def accuracy(y, y_hat):
    # Assign each y_hat to its predicted class
    pred_classes = torch.where(y_hat < .5, 0, 1).squeeze().long() #squeeze deletes all singleton dimensions, eg a vector [4,1] -> [4]
    correct = (pred_classes == y).sum()
    return (correct / y.shape[0]).item()

In [20]:
accuracy(y, y_hat)

0.30000001192092896

#### Visualizing linear and logistic regression as a computational graph

We now need to convert the equation of the linear and the logistic regression:
* `y = σ(WX + b)`

where `σ` is a generic `ℝ → ℝ` function: sigmoid for logistic regression, identity for linear regression.

![](imgs/01/log_reg_graph.jpg)

We organize the input in *nodes* (on the left part) s.t. each node represents one dimension/covariate.
For each data instance, we substitute to each node the corresponding numeric value.
The nodes undergo one or more operations, namely, from left to right:

1. Each node is multiplied by its corresponding weight (a value placed on the edge indicates that the node is multiplied by said value)
2. All the corresponding outputs are summed together

These two operations identify the dot product between vectors `X` and `W`

3. The bias term `b` is added
4. The non-linear function `σ` is applied to the result of this sum
5. Finally, we assign that value to the variable `ŷ`, which is also indicated as a node

**Q**: what is the relationship between $b$ and $X_4$?

b being the bias can be interpreted as the weight of an input which is fixed to 1

### Our first MultiLayer Perceptron (MLP)

The MLP is a family of Artificial NNs in which the input is a vector of size `ℝ^d` and the output is again a vector of size `ℝ^p`, where `p` is determined upon the nature of the problem we wish to solve. Additionally, a MLP is characterized by multiple stages (*layers*) of sequential vector-matrix multiplication and non-linearity (steps 1., 2., 3. above) in which each output of the layer `l-1` acts as input to the layer `l`.

Taking inspiration to the graph of the logistic regression, we can translate all into an image to give sense to these words:

![](imgs/01/mlp_graph.jpg)

In NNs, each of the nodes within the graph is called a **neuron**

Neurons are organized in **layers**

In computational graphs, layers are shown from left to right (or bottom to top sometimes), which is the direction of the flow of information inside the NN.

The first layer is called **input layer** and represents the dimensions of our data.

The last layer is called **output layer** and represent the output of our NN.

All the intermediate layers are called **hidden layers**. To be defined MLP, there must be at least one hidden layer inside our model.

If the NN is an MLP, each neuron in a given layer (except for the input) receives information from every neuron of the previous; moreover, each neuron in any layer (except for the output) sends information to every neuron of the next layer. There's no communication between neurons of the same layer (if it happens, we have a **Recursive Neural Network**).

For the sake of brevity, usually in NN computational graphs we drop the blocks `+` and `σ`, the values of weights, and the reference to the bias terms, remaining with a scheme conveying info about
* the number of neurons per layer
* the connectivity of neurons

The graph above becomes:

![](imgs/01/mlp_graph_common.jpg)

We can then start programming our simple MLP in PT.

We will suppose that our MLP is for **binary classification**, hence the activation function `τ` is the sigmoid.

In [21]:
class MLP(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = torch.nn.Linear(in_features=3, out_features=2)
        self.layer2 = torch.nn.Linear(in_features=2, out_features=1)

    def forward(self, X):
        out = self.layer1(X)
        out = torch.nn.functional.relu(out)
        out = self.layer2(out)
        out = torch.nn.functional.sigmoid(out)
        return out


For the great majority of MLP, it's very hard to get analytical solutions to our sets of weights and biases. We then resort to numerical methods for optimization.

In DL, we normally used gradient-based methods like Stochastic Gradient Descent with *backpropagation* to find approximate solutions.

We'll cover these topics in future lectures. For now, the focus is to build a MLP in PT and perform the *forward pass* (=evaluate the model on a set of data).

We can analyse the structure of our MLP by just printing the model

In [22]:
model = MLP()
model

MLP(
  (layer1): Linear(in_features=3, out_features=2, bias=True)
  (layer2): Linear(in_features=2, out_features=1, bias=True)
)

although we might wanna have additional informations.

There's an additional package, called `torchinfo` which helps us producing more informative and exhaustive model summaries.

We can install it from the terminal:

- activate the conda env
- `conda install -c conda-forge torchinfo`

On Colab, remember that you can execute bash commands prepending a `!` to the command itself.

In [25]:
from torchinfo import summary
summary(model)

Layer (type:depth-idx)                   Param #
MLP                                      --
├─Linear: 1-1                            8
├─Linear: 1-2                            3
Total params: 11
Trainable params: 11
Non-trainable params: 0

#### Usage of `Sequential`

If we have a neural network whose forward pass just processes the layers in sequence in a given order, we can also wrap the layers inside a `torch.nn.Sequential` structure.

Note that:
1. In this case, all the activation functions must be passed as their `nn.Module` counterpart, not as `torch.nn.functional` functions
2. The data flows in the layers according to the order dictated in the constructor

**Q**: How can I build the `forward` method now?


In [29]:
class MLP(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(3, 2),
            torch.nn.ReLU(),
            torch.nn.Linear(2, 1),
            torch.nn.Sigmoid()
        )

    def forward(self, X):
        return self.layers.forward(X)



Let us suppose we wish to build a larger model from the graph below.

![](imgs/01/mlp_graph_larger.jpg)

We suppose that

1. The layers have no bias units
2. The activation function for hidden layers is `ReLU`

    $ \text{ReLU}(x) = \max(0, x)$

Moreover, we suppose that this is a classification problem.

As you might recall, when the number of classes is > 2, we encode the problem in such a way that the output layer has a no. of neurons corresponding to the no. of classes. Doing so, we establish a correspondence between output units and classes. The value of the $j$-th neuron represents the **confidence** of the network in assigning a given data instance to the $j$-th class.

Classically, when the network is encoded in such way, the activation function for the final layer is the **softmax** function.
If $C$ is the total number of classes,

$softmax(z_j) = \frac{\exp(z_j)}{\sum_{k=1}^C \exp(z_k)}$

where $j\in \{1,\cdots,C\}$ is one of the classes.

If we repeat this calculation for all $j$ s, we end up with $C$ normalized values (i.e., between 0 and 1) which can be interpreted as a confidence that the network has in assigning the instance to the corresponding class.

#### Homework

1. build the MLP in the image above using PT built-ins
2. Provide calculation for the exact number of parameters of the MLP
   - Do it first supposing that the layers don't have a bias term, then supposing that the bias is present wherever it's possible
3. Calculate the $L_1$ (vectorial) norm and the Frobenius norm for the params of each layer
4. Given 10 random datapoints, feed them into the network. This operation must be done all in one single command and must **not** make use of loops.
   - Given the output of the network, using PyTorch code, find the class of assignment of each datapoint. This also must be done in a single PyTorch command without using loops.
   - Drafting a vector of ground truths (whichever labels you like), provide code for the calculation of the accuracy
     - Tip: first get the number of correct assignments, then...